[package]
name = "catalog"
version = "0.1.0"
authors = ["Tim Patterson <tim.wanaka@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
data = { path = "../data" }
storage = { path = "../storage" }